// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-kEr8ZDWjiM9u1atnAJbwti2oxpOcHg8',
    appId: '1:497265222573:web:a0e09517f6d7834fa3f724',
    messagingSenderId: '497265222573',
    projectId: 'managetmantmotel',
    authDomain: 'managetmantmotel.firebaseapp.com',
    storageBucket: 'managetmantmotel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeL_WEl_Qf-ZSk89y60PVNYLvFBpDzPao',
    appId: '1:497265222573:android:c01d542b57f45801a3f724',
    messagingSenderId: '497265222573',
    projectId: 'managetmantmotel',
    storageBucket: 'managetmantmotel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaEytG9lBzlb3LzIbxUXIYbHCIFZL17rU',
    appId: '1:497265222573:ios:7c9fdc21d3642a5ca3f724',
    messagingSenderId: '497265222573',
    projectId: 'managetmantmotel',
    storageBucket: 'managetmantmotel.firebasestorage.app',
    iosBundleId: 'com.example.motelapp',
  );

}