// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYkxdXQtAMu3zRMR9uR6qolYYXHKpf7I',
    appId: '1:820340378898:web:ed8e87e505bd49fe7fb7cb',
    messagingSenderId: '820340378898',
    projectId: 'motelapp-4eb18',
    authDomain: 'motelapp-4eb18.firebaseapp.com',
    storageBucket: 'motelapp-4eb18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoji3_n85QSejnyFzOOTIvxOW-czPRp40',
    appId: '1:820340378898:android:0bbb44e55e5320ca7fb7cb',
    messagingSenderId: '820340378898',
    projectId: 'motelapp-4eb18',
    storageBucket: 'motelapp-4eb18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYsk8QpmXHJUdlgr4WL7tB8CIkFjdEtw',
    appId: '1:820340378898:ios:ae1d40903d2bf3bf7fb7cb',
    messagingSenderId: '820340378898',
    projectId: 'motelapp-4eb18',
    storageBucket: 'motelapp-4eb18.firebasestorage.app',
    iosBundleId: 'com.example.motelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGYsk8QpmXHJUdlgr4WL7tB8CIkFjdEtw',
    appId: '1:820340378898:ios:ae1d40903d2bf3bf7fb7cb',
    messagingSenderId: '820340378898',
    projectId: 'motelapp-4eb18',
    storageBucket: 'motelapp-4eb18.firebasestorage.app',
    iosBundleId: 'com.example.motelapp',
  );
}
